### PR TITLE
GH Star button

### PR DESCRIPTION
**Pull request by joaquimg**
I could not build locally so I dont know if its properly placed.

### CODE REVIEW

**Comment by odow** [comment]
I don't think this is what you intended:

image

**Comment by joaquimg** [comment]
Actually was about that, no strong feelings though.
Slightly inspired in julialang page.
I had not much chance of experimenting other stuff since I could not build.

**Comment by odow** [comment]
> since I could not build

Ah, yeah. IIRC, getting ruby and Jekyll setup on Windows was a pain.

**Comment by odow** [comment]
Closing as stale. It's probably hard to get this working with our current setup.

**Pull request closed without merging**
