### PR TITLE
Add learn.md

### LINKED ISSUE #75: Add links to educational materials and classes
We may want to have pages like https://julialang.org/learning/ and https://julialang.org/learning/classes/ to list classes using JuMP and other educational materials. (IIRC, we intentionally skipped this in the first pass of the website.)

### PR DESCRIPTION
**Pull request by odow**
Closes #75

List taken from http://www.juliaopt.org/showcase/. Ideally, we would update this, and include links, but I couldn't find many by Googling.

### CODE REVIEW

**Comment by mlubin** [comment]
As is, the list of universities using JuMP doesn't provide any learning materials. We should list only courses that we can link to.

**Comment by odow** [comment]
Do we know any that are up-to-date?

**Comment by mlubin** [comment]
> Do we know any that are up-to-date?

Not on the top of my mind. We'll have to ask around. (Doesn't need to block this PR.)

**Comment by odow** [comment]
Okay. I've removed the section for now

**Comment by dourouc05** [comment]
Quite a few years ago, I've released https://github.com/dourouc05/OptimisationTeachingKit, which was what I was using for a class (2015-2017), including solutions for modelling problems in Julia with JuMP. Since then, it's been updated, I think it should work with the latest JuMP versions (nothing fancy in the syntax).

**Comment by jd-foster** [comment]
This is nice. Could be worth a call out on discourse and gitter to find out others.

**Comment by pulsipher** [comment]
I am aware this older resource from UW-Madison: https://laurentlessard.com/teaching/524-intro-to-optimization/ (it uses JuMP 0.18 though). Line Roald has since taken over the course for the past few years along with Stephen Wright (both use JuMP), but I don't think they have a public link for their notes.

**Comment by noahrhodes** [comment]
I'm the TA for 524 Intro to Optimization at UW-Madison.  We are currently using JuMP 0.23/1.0 in the class,  but I don't think there is any public link for that.

**Comment by matbesancon** [comment]
pinging @sevaux and @xgandibleux in case they have JuMP-specific materials

**Comment by xgandibleux** [comment]
I have given a course last year at JKU-Linz where the chapter 7 is devoted to JuMP (here the slides and exercices: https://julialang.univ-nantes.fr/julianantes/documents/). I am currently working on it since I will give this course in 4 weeks, and I am refactoring my content to set JuMP more central in the course (and to reduce the aspects related to Julia) to match better with the profile of this public

For my students at Nantes University, I have several supports, but in general they are bootstraps for projects e.g. this one on the set packing problem, https://github.com/xgandibleux/metaSPPstu (JuMP is one part of this project but it is not central since this material comes from my course on metaheuristics). 

Same for our course on Operations Research given at Nantes where JuMP is here central into the projects developed by the students (each year the project is different and we provide the bootstraps but not the models in JuMP since it is a part of the work to do by the students).

**Comment by odow** [comment]
Here's what it looks like at the moment:

image

**Comment by odow** [comment]
Merging. We can fix anything in a new PR.

**Pull request merged**
