### PR TITLE
Add PSR blog post

### PR DESCRIPTION
**Pull request by odow**
cc @joaquimg let me know what changes you'd like.

### CODE REVIEW

**Comment by joaquimg** [comment]
Looks great!

The only extra thing I would add is the link to project website: https://www.meta2formacaodepreco.com.br/ somowhere.
In particular, JuMP is mentioned here: https://www.meta2formacaodepreco.com.br/software
It is in Portuguese, but Google Translate is pretty good and @mlubin speaks Portuguese :)

We added the JuMP logo in the second link. So, although it's there already, I would like to have approval to keep it over there.

**Comment by odow** [comment]
I'll add the link.

I approve the use of the SDDP.jl logo, and the JuMP one also looks good. But Miles should comment as well.

**Comment by odow** [comment]
image

**Review by mlubin — APPROVED** [review]

**Comment by mlubin** [comment]
The use of the JuMP logo seems fine. The page is listing the open source software packages used in the project.

**Pull request merged**
